config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :skip => [:registrations]
#, controllers: {:registrations => "users/registrations"}

  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
  get 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session_path
  get "/sign_up" => "users#new", as: :new_user_path
  end


  resources :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  resources :applies, only: [:new, :create]



  get "/pages/:page" => "pages#show"
  get 'welcome/index'
  get 'topic-help' => 'pages#topic'
  get '/apply' => 'contacts#new'


  root 'welcome#index'
  get '*path' => redirect('/')
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :full_name, use: :slugged
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts


    validates :full_name, presence: true

    validates :email, presence: true

  def should_generate_new_friendly_id?
    slug.blank? || full_name_changed?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def new
     super
   end

   def create
     self.resource = warden.authenticate!(auth_options)
     set_flash_message(:notice, :signed_in)
     sign_in(resource_name, resource)
     if !session[:return_to].blank?
       redirect_to session[:return_to]
       session[:return_to] = nil
     else
       respond_with resource, :location => after_sign_in_path_for(resource)
     end
   end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:show, :edit]
  #before_action :is_admin?, only: [:index]
  #load_and_authorize_resource




  def show
    @user = User.friendly.find(params[:id])
    @user_posts = @user.posts.all.order("created_at desc")
    @posts = Post.all.order("created_at desc")
  end

  def index
    @users = User.all.order("created_at desc")
  end

  def edit
  end

  def new
    @user = User.new
    @user.save

  end

  def create
    @user = User.new(user_params)
    @user.save

    if @user.save
      redirect_to root_path, notice: "Your changes were successfully saved!"
    else
      render 'new', notice: "Oh no! Your changes were not able to be saved!"
    end
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to root_path, notice: "Your changes were saved!"
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end
  def is_admin?
    redirect_to root_path unless (current_user && (current_user.admin?))
  end
  def should_generate_new_friendly_id?
     full_name_changed?
   end
  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :full_name, :slug, :admin)
  end

  def find_user
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<% if @user.errors.any? %>
  <h2><%= pluralize(@user.errors.count, "error")%> prevented this post from saving:</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= f.label :full_name, "Full Name" %>
<%= f.text_field :full_name %>

<%= f.label "Upload profile picture" %><br><br />
<%= f.file_field :profile %><br/><br/>
<br>



<%= f.label "Email (Will not be published)" %><br>
<%= f.text_field :email %>


<% if current_user && current_user.admin? %>
<%= f.label "Admin" %>
<%= f.check_box :admin %><br />
<% end %>


<br><%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h1 id="form_title">Edit Profile</h1>

<div class="skinny_wrapper wrapper_padding" style="max-width: 1000px;">

<%= render 'form' %>

</div>

app/views/users/index.html.erb
<h1 id="form_title" style="margin-bottom: -80px; margin-top:-50px; border-bottom: none;">Users</h1>



<div id="posts_wrapper" class="skinny_wrapper">

  <%= link_to "New User", new_user_path, :class => "link--edit" %>

</div>

app/views/users/new.html.erb
<div id="posts_wrapper" class="skinny_wrapper">
  <% if current_user.admin? %>

  <h1 id="form_title">Add User</h1>

  <%= form_for @user do |f| %>

    <div class="field">
      <%= f.label "Full name" %>
      <%= f.text_field :full_name %>

      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <br><%= f.submit %>

  <% end %>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div id="posts_wrapper" class="skinny_wrapper">
  <h1 id="form_title" style="margin-top: 20px;">Profile Preview</h1>

<br>
<div class="flex--p">
  <p>You're signed in as <%= @user.full_name %></p>
</div>
<br><br><br><br>
  <h1 id="sub_title" style="margin-top: 40px;">Your Published Articles</h1>
  <div class="post-list">


    <% @user_posts.approved.each do |post| %>
    <div class="flex--postlist--item">
      <div class="inside--item">
          <h6 id="post-title"><a href="#"><%= link_to post.title, post%></a></h6>
      </div>
      <h6 id="date"><%= post.created_at.strftime('%A, %B %d') %></h6>
    </div>
    <% end %>
      </div>
<br>

      <h1 id="sub_title" style="margin-top: 40px;">Your Unfinished Articles</h1>
      <div class="post-list">


        <% @user_posts.each do |post| %>
          <% if post.approved? == false && post.waiting_for_approval == false %>
        <div class="flex--postlist--item">
          <div class="inside--item">
              <h6 id="post-title"><a href="#"><%= link_to post.title, post%></a></h6>
          </div>
          <h6 id="date"><%= post.created_at.strftime('%A, %B %d') %></h6>
        </div>
        <% end %>
        <% end %>

          </div>
<br>
          <h1 id="sub_title" style="margin-top: 40px;">Waiting to Be Published</h1>
          <div class="post-list">


            <% @user_posts.waiting_for_approval.each do |post| %>
            <div class="flex--postlist--item">
              <div class="inside--item">
                  <h6 id="post-title"><a href="#"><%= link_to post.title, post%></a></h6>
              </div>
              <h6 id="date"><%= post.created_at.strftime('%A, %B %d') %></h6>
            </div>
            <% end %>

              </div>




  <% if (current_user.admin?) %>
      <h1 id="form_title" style="margin-top: 40px;">All: Waiting for approval</h1>
      <% @posts.each do |post| %>
      <% if post.waiting_for_approval? %>
      <div class="flex--postlist--item">
        <div class="inside--item">
            <h6 id="post-title"><a href="#"><%= link_to post.title, post%></a></h6>
        </div>
        <h6 id="date"><%= post.created_at.strftime('%A, %B %d') %></h6>
      </div>
      <% end %>
        <% end %>
        <% end %>


      </div>

<br>


<%= link_to "New Post", new_post_path(@post), :class => "newpost--profile" %> <br><br><br>
<%= link_to "Edit User", edit_user_path(@user), :class => "newpost--profile" %>   </p>



<br><br>


</div>

<div class="guidelines">
  <div class="thelink">
    <a href="/pages/criteria">
    <div class="box foo G1 ">
      <p>Things to Know</p>
    </div>
    </a>
  </div>
  <div class="thelink">
    <a href="/pages/topic">
      <div class="G2 box foo">
        <p>Choosing A Topic</p>
      </div>
    </a>
  </div>
  <div class="thelink">
    <a href="/pages/first-article">
      <div class="G3 box foo">
        <p>Your First Article</p>
      </div>
    </a>
  </div>
  <div class="thelink">
    <a href="/pages/images">
      <div class="G5 box foo">
        <p>Finding Images</p>
      </div>
    </a>
  </div>
</div>