config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :skip => [:registrations]
#, controllers: {:registrations => "users/registrations"}

  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
  get 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session_path
  get "/sign_up" => "users#new", as: :new_user_path
  end


  resources :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  resources :applies, only: [:new, :create]



  get "/pages/:page" => "pages#show"
  get 'welcome/index'
  get 'topic-help' => 'pages#topic'
  get '/apply' => 'contacts#new'


  root 'welcome#index'
  get '*path' => redirect('/')
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
    @post_first = Post.order("created_at").last

end

def show
  set_meta_tags title: 'Consonancie',
                description: 'Your source for the latest humor, entertainment, trends, tips, and advice '
end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">window.dojoRequire(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us20.list-manage.com","uuid":"6f0a53bc68ffca43b5082f63c","lid":"59281fb7a2","uniqueMethods":true}) })</script>

  <% filteredPosts = [] %>
  <!--filtered posts are supposed to be approved -->
  <% Post.approved.all.order("created_at desc").each do |post| %>
    <% filteredPosts.push post %>
  <% end %>




<div class="featured_img">
   <%= link_to filteredPosts[0] do %>
   <%= image_tag (filteredPosts[0].thumbnail.url(:large)), :style => '', class: "featured_img1" %>
    <div class="main_hdr">

      <h3><a href="#"><%= link_to filteredPosts[0].title, filteredPosts[0] %></a> </h3>
      <div class="post_index_details">
        <p class="post_date"><%= filteredPosts[0].created_at.strftime('%A, %B %d') %></p>
        <p class="post_date">BY <%= filteredPosts[0].user.full_name %></p>
      </div>
    <h3 id="under_post"><%=  markdown(filteredPosts[0].content[3,200]) %>...</h3>

    </div>

    <% end %>
</div>



<div class="flex--welcome">
    <div class="trending-new">
      <div class="section">
        <div class="one-article" style="width: 33%;">
          <%= link_to filteredPosts[1] do %>
          <%= image_tag (filteredPosts[1].thumbnail.url(:large)), class: "home_image" %>
          <h3><a href="#"><%= link_to filteredPosts[1].title, filteredPosts[1] %></a></h3>
          <p><%= filteredPosts[1].created_at.strftime("%A, %b %d")%></p>
          <p class="desc"><%= markdown(filteredPosts[1].content[3, 250]) %> </p>
          <% end %>
        </div>
        <div class="one-article" style="width: 33%;">
          <%= link_to filteredPosts[2] do %>
          <%= image_tag (filteredPosts[2].thumbnail.url(:large)), class: "home_image" %>
          <h3><a href="#"><%= link_to filteredPosts[2].title, filteredPosts[2] %></a></h3>
          <p><%= filteredPosts[2].created_at.strftime("%A, %b %d")%></p>
          <p class="desc"><%= markdown(filteredPosts[2].content[3,300]) %> </p>
          <% end %>
        </div>
        <div class="one-article" style="width: 33%;">
          <%= link_to filteredPosts[3] do %>
            <%= image_tag (filteredPosts[3].thumbnail.url(:large)), class: "home_image" %>
            <h3><a href="#"><%= link_to filteredPosts[3].title, filteredPosts[3] %></a></h3>
            <p><%= filteredPosts[3].created_at.strftime("%A, %b %d")%></p>
            <p class="desc"><%= markdown(filteredPosts[3].content[3,300]) %> </p>
            <% end %>
        </div>
    </div>
</div>
</div>


















<div class="hr_color1">

</div>
<div class="hr_color2">

</div>
<div class="hr_color3">

</div>
<div class="welcome">
  <div class="whole_category">
    <div class="articles-show">
      <div class="flex">
        <div class="container_show">
          <% filteredPosts[4..-1].each do |post| %>
              <div class="whole_post">
                  <div class="container_image">
                    <%= image_tag (post.thumbnail.url(:large))%>
                  </div>
                  <div class="post_content">
                    <p class="post_date"><%= post.created_at.strftime('%A, %B %d') %></p>
                    <h2><a href="#"> <%= link_to post.title, post %> </a></h2>
                    <div class="post_index_details">
                    <p class="post_date">BY <%= post.user.full_name %></p>
                    </div>
                  </div>
             </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!--
<div class="recent_posts">
  <div id = "welcome_posts" class="skinny_wrapper posts_wrapper">

  <% filteredPosts[4..-1].each do |post| %>

      <div class="post" id="welcome_post">
        <div class="flex">

      <%= image_tag (post.thumbnail.url(:large)), class: "posts_show_img", id: "posts_show_img_wel"%>
      <p class="date_trending" id="date_trending_wel"><%= post.created_at.strftime('%A, %B %d') %></p>
      <h2><a href="#"> <%= link_to post.title, post %> </a></h2>
        </div>

      <% post.category_id do |category| %>
      <li>
      <%= link_to category.name, posts_path(category: category.name) %>
      </li>

    <% end %>




  </div>

<% end %>


  </div>


</div> -->