config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :skip => [:registrations]
#, controllers: {:registrations => "users/registrations"}

  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
  get 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session_path
  get "/sign_up" => "users#new", as: :new_user_path
  end


  resources :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  resources :applies, only: [:new, :create]



  get "/pages/:page" => "pages#show"
  get 'welcome/index'
  get 'topic-help' => 'pages#topic'
  get '/apply' => 'contacts#new'


  root 'welcome#index'
  get '*path' => redirect('/')
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @projects = Project.all.order("created_at desc")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    if @project.save
      redirect_to @project, notice: "Your project was successfully saved!"
    else
      render 'new'
    end
  end

  def show

  end

  def edit
  end

  def update
    if  @project.update project_params
      redirect_to @project, notice: "Your project was successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <h2><%= pluralize(@project.errors.count, "error")%> prevented this project from saving:</h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %> <br>
  <%= f.text_field :title %>
  <br>
  <br>

  <%= f.label :description %> <br>
  <%= f.text_area :description %>

  <br>
  <br>

  <%= f.label :link %> <br>
  <%= f.text_field :link %>
  <br>
  <br>

  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edit Project</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Stuff I've Built</h1>
<div id="posts_wrapper" class="skinny_wrapper">

<% @projects.each do |project| %>
  <div class="post">
    <p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
    <h2><a href="#"> <%= link_to project.title, project %> </a></h2>
    <hr>
  </div>
<% end %>


</div>

app/views/projects/new.html.erb
<h1 id="page_title">New Project</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @project.created_at.strftime("%A, %B %d")%></p>
    <h1><%= @project.title %></h1>
    <hr>
  </header>
<div id="content">
  <%= markdown @project.description  %>

  <div class="button_wrapper">
  <a href="<%= @project.link %>" class="project_button" target="_blank"> Visit <%= @project.title %> </a>
  </div>

</div>

<% if user_signed_in? %>
  <div id="admin_links">
    <%= link_to "Edit", edit_project_path(@project) %>
    <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
<% end %>


<hr>
</div>