config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :skip => [:registrations]
#, controllers: {:registrations => "users/registrations"}

  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
  get 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session_path
  get "/sign_up" => "users#new", as: :new_user_path
  end


  resources :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  resources :applies, only: [:new, :create]



  get "/pages/:page" => "pages#show"
  get 'welcome/index'
  get 'topic-help' => 'pages#topic'
  get '/apply' => 'contacts#new'


  root 'welcome#index'
  get '*path' => redirect('/')
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_attached_file :thumbnail, styles: {large: "600x600>", medium: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/
  validates :title, :content, :category_id, presence:true

  belongs_to :user


  scope :approved, -> {
  where(approved: true)
  }
  scope :waiting_for_approval, -> {
  where(waiting_for_approval: true, approved: false)
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  load_and_authorize_resource





  def index
    if params[:category].blank?
      @posts = Post.approved.all.order("created_at desc")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @posts = Post.approved.where(category_id: @category_id).order("created_at DESC")

  end
  end





  def new
    if user_signed_in?
     @post = current_user.posts.build
   else
     @post = Post.new
   end
 end


 def create
   if user_signed_in?
     @post = current_user.posts.build(post_params)
   else
     @post = Post.new(post_params)
   end

   if @post.save && @post.approved
     redirect_to @post, notice: "Congrats! Your post was successfully published!"
   elsif @post.save
     redirect_to @post, notice: "Changes were successfully saved!"
   else
     render 'new', notice: "Oh no! Your post was not able to be saved!"
   end
 end

  def show

    redirect_to root_path unless (@post.approved || (current_user && (@post.user_id == current_user.id ||  current_user.admin?)))
    @users = User.all.order("created_at desc")
    set_meta_tags title: @post.title,
                  description: @post.meta_description,
                  keywords: @post.keywords


  end


  def edit
  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "Your article was successfully saved!"
    else
      render "edit"
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :thumbnail, :image, :slug, :category_id, :meta_description, :author, :waiting_for_approval, :approved)
  end
  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">



(function() { // DON'T EDIT BELOW THIS LINE
var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
dsq.src = '//' + disqus_shortname + 'disqus.com/embed.js';
(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0].appendChild(disq)})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error")%> prevented this post from saving:</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :category_id, "Choose a Category" %> <br><br>
<%= f.collection_select(:category_id, Category.all, :id, :name) %><br><br>
  <%= f.label :thumbnail, "Upload a thumbnail image" %> <br><br>
  <%= f.file_field :thumbnail %>
  <br> <br>
  <br>
  <%= f.label :title, "Enter the post title" %><br>
    <%= f.text_field :title %><br>
  <br>
  <br>

  <%= f.label :content, "Write your article here" %> <br>
  <%= f.cktext_area :content %>

  <br>
  <br>



  <% if @post.approved == true %>
      <br><%= f.submit "Publish Changes" %>
  <% else %>
    <br><%= f.label "Submit My Article For Approval" %>
    <%= f.check_box :waiting_for_approval %><br>
    <%= f.hidden_field :approved, :value => false %><br>
    <br><%= f.submit "Save & Preview" %>
  <% end %>



<br>


  <% if (current_user && (current_user.admin?)) %>
  <br><%= f.label "Approve" %>
  <%= f.check_box :approved %><br /><br />
  <% end %>







<% end %>

app/views/posts/_nav.html.erb
<% Category.all.each do |category| %>
  <li>
  <%= link_to category.name, posts_path(category: category.name) %>
  </li>
<% end %>

app/views/posts/edit.html.erb
<h1 id="form_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render "form" %>
</div>

app/views/posts/index.html.erb
<div class="posts-show-category">
  <h2 id = "page_title"><%= Category.find_by(name: params[:category]).name %> </h2>
</div>

<div class="whole_category">
  <div class="articles-show">
    <div class="flex">
      <div class="container_show">
          <% @posts.approved.each do |post| %>
            <div class="whole_post">
                <div class="container_image">
                  <%= image_tag (post.thumbnail.url(:large))%>
                </div>
                <div class="post_content">
                  <p class="post_date"><%= post.created_at.strftime('%A, %B %d') %></p>
                  <h2><a href="#"> <%= link_to post.title, post %> </a></h2>
                  <div class="post_index_details">
                  <p class="post_date">BY <%= post.user.full_name %></p>
                  </div>
                </div>
           </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1 id="form_title">New Post</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render "form" %>
</div>

app/views/posts/show.html.erb
<header>
  <h1 class="post_title" id="post_show_title"><%= @post.title %></h1>
  <div class="date_posts_show">
  <p id="date_post"><%= @post.created_at.strftime("%A, %B %d") %></p>
  <p class="author">By <%=@post.user.full_name%></p>
</div>

<%= image_tag @post.thumbnail.url, :class => "show_thumbnail" %>

</header>


<div id="post_show_content" class="skinny_wrapper wrapper_padding">


<div id="content">
  <%= raw @post.content %>
</div>

<% if can? :update, @post %>
  <div id="admin_links">
  <%= link_to "Edit Article", edit_post_path(@post) %>
  <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
<%end%>


<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://gmail.us20.list-manage.com/subscribe/post?u=6f0a53bc68ffca43b5082f63c&amp;id=59281fb7a2" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe to our Newsletter!</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_6f0a53bc68ffca43b5082f63c_59281fb7a2" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->

</div>


<%= render 'disqus' %>

<br>
<br>